apiVersion: v1
kind: Service
metadata:
  name: {{ include "danube-envoy.fullname" . }}
  labels:
    {{- include "danube-envoy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - name: admin
      port: 9901
      targetPort: admin
      protocol: TCP
  selector:
    {{- include "danube-envoy.selectorLabels" . | nindent 4 }}
