# Default values for danube-helm-chart.

# Global settings
replicaCount: 1

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: broker1.example.com
    - host: broker2.example.com
    - host: broker3.example.com
  tls: []

# ETCD configuration
etcd:
  name: etcd
  enabled: true
  replicaCount: 1
  image:
    repository: bitnami/etcd
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 2379

# Broker configuration
broker:
  name: danube
  adminHost: broker1.example.com
  instances:
    - name: broker1
    - name: broker2
    - name: broker3
  image:
    repository: ghcr.io/danrusei/danube-broker
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    brokerPort: 6650
    adminPort: 50051
    promPort: 9040
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    RUST_LOG: danube_broker=info

# Broker configuration file content
brokerConfig:
  configFile: |
    cluster_name: "MY_CLUSTER"
    broker_host: "0.0.0.0"
    broker_port: 6650
    admin_port: 50051
    prom_port: 9040
    meta_store_host: "my-danube-cluster-etcd"
    meta_store_port: 2379
    bootstrap_namespaces: ["default"]
    policies:
      max_producers_per_topic: 0
      max_subscriptions_per_topic: 0
      max_consumers_per_topic: 0
      max_consumers_per_subscription: 0
      max_publish_rate: 0
      max_dispatch_rate: 0
      max_subscription_dispatch_rate: 0
      max_message_size: 10485760
