apiVersion: v2
name: danube-connector
description: Generic chart for deploying Danube source and sink connectors
icon: https://raw.githubusercontent.com/danube-messaging/danube/main/wave.png
type: application
version: 0.1.0
appVersion: "v0.2.1"
