{{- if and .Values.secretEnv (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "danube-connector.fullname" . }}-secret
  labels:
    {{- include "danube-connector.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
