apiVersion: v2
name: danube-ui
description: Admin server and web UI for Danube messaging cluster
icon: https://raw.githubusercontent.com/danube-messaging/danube/main/wave.png
type: application
version: 0.1.0
appVersion: "v0.7.3"
