apiVersion: v1
kind: Service
metadata:
  name: {{ include "danube-ui.admin.name" . }}
  labels:
    {{- include "danube-ui.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
spec:
  type: {{ .Values.admin.service.type }}
  ports:
    - name: http
      port: {{ .Values.admin.service.port }}
      targetPort: http
  selector:
    {{- include "danube-ui.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admin
