{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "danube-ui.frontend.name" . }}
  labels:
    {{- include "danube-ui.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      targetPort: http
      {{- if and (eq .Values.ui.service.type "NodePort") (not (empty .Values.ui.service.nodePort)) }}
      nodePort: {{ .Values.ui.service.nodePort }}
      {{- end }}
  selector:
    {{- include "danube-ui.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
