{{- if and .Values.prometheus.enabled .Values.prometheus.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "danube-core.prometheus.name" . }}
  labels:
    {{- include "danube-core.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "danube-core.prometheus.name" . }}
  labels:
    {{- include "danube-core.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "danube-core.prometheus.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "danube-core.prometheus.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
