{{- if and .Values.prometheus.enabled .Values.prometheus.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "danube-core.prometheus.serviceAccountName" . }}
  labels:
    {{- include "danube-core.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
{{- end }}
