{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "danube-core.prometheus.name" . }}
  labels:
    {{- include "danube-core.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.prometheus.service.port }}
      targetPort: http
  selector:
    {{- include "danube-core.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
{{- end }}
